services:
  backend1:
    build: ./backend
    environment:
      - PORT=3000
      - SERVER_ID=backend-1
      - DATABASE_URL=postgresql://postgres:postgres@host.docker.internal:5432/practice24
      - MONGO_URL=mongodb://mongo:27017/techmarket
      - REDIS_URL=redis://redis:6379
      - ACCESS_SECRET=access_secret_key_techmarket
      - REFRESH_SECRET=refresh_secret_key_techmarket
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app-network
    depends_on:
      - mongo
      - redis

  backend2:
    build: ./backend
    environment:
      - PORT=3000
      - SERVER_ID=backend-2
      - DATABASE_URL=postgresql://postgres:postgres@host.docker.internal:5432/practice24
      - MONGO_URL=mongodb://mongo:27017/techmarket
      - REDIS_URL=redis://redis:6379
      - ACCESS_SECRET=access_secret_key_techmarket
      - REFRESH_SECRET=refresh_secret_key_techmarket
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app-network
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:7
    networks:
      - app-network
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    networks:
      - app-network

  frontend:
    build: ./frontend
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - backend1
      - backend2
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data:
